services:
  redis:
    image: redis:alpine
    container_name: downloaderbot-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Memory limit
    deploy:
      resources:
        limits:
          memory: 256M
  worker:
    container_name: downloaderbot-worker
    build:
      context: .
      dockerfile: ../DownloaderBot.Worker/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis
      - BOT_TOKEN=${BOT_TOKEN}
  api:
    build:
      context: .
      dockerfile: ../DownloaderBot.Api/Dockerfile
    container_name: downloaderbot-api
    restart: always
    depends_on:
      - redis
    ports:
      - "5189:8080"
    environment:
      - REDIS_CONNECTION=redis
      - BOT_TOKEN=${BOT_TOKEN}

volumes:
  redis_data: